FROM rust:1.72.0 as build
ENV PKG_CONFIG_ALLOW_CROSS=1

WORKDIR /usr/src/web-service
COPY . .

RUN cargo install --path .

FROM gcr.io/distroless/cc-debian12

COPY --from=build /usr/local/cargo/bin/web-service /usr/local/bin/web-service

CMD ["web-service"]
